### PR TITLE
split up app/lib

### PR DESCRIPTION
**Pull request by aSemy**
Another preparation PR for #1 

* Creates a new subproject, `:app` (with the same Maven coordinates as the currently published artifact) that contains the CLI application. The ABI has been maintained for backwards compatibility, but the functionality has been moved to a new class in `:lib`.
* the Maven coordinates of `:lib` have been updated to have an artifact name `urlencoder-lib`

### CODE REVIEW

**Comment by ethauvin** [comment]
@aSemy FYI. SonarCloud plugin is failing with:

```
* What went wrong:
Execution failed for task ':app:sonar'.
> Project not found. Please check the 'sonar.projectKey' and 'sonar.organization' properties, the 'SONAR_TOKEN' environment variable, or contact the project administrator
```

**Comment by aSemy** [comment]
hi @ethauvin, based on this post I guess there's a problem with the permissions in the Sonar website

> Hey, this might be relevant to future visitors:
>
> If you were the one who generated the token, check (yourself or with an admin) whether you have the "**Execute Analysis**" permission on your SonarCloud user, and **specifically for the project** you are trying to run an analysis on. I had the same issue and managed to fix it by applying the permissions.
>
> The only logic I see behind this misleading error is that, without the permissions, the project is “hidden” and deemed not found. The error should instead mention a lack of permissions…
>
> Hope this helped!
>
> _https://community.sonarsource.com/t/project-not-found-please-check-the-sonar-projectkey-and-sonar-organization-properties/67544/6_

**Comment by ethauvin** [comment]
@aSemy It worked just fine with my updates and the first PR. Something is different with this PR. Haven't really figured out what though.

It doesn't work locally either, where the token, etc. are in the `gradle.properties` file.

**Comment by aSemy** [comment]
That's weird. I've not used Sonar in a long time. Perhaps there's a problem because the project path is different? Or maybe because there are two subprojects that have the same `sonar.projectName` and `sonar.projectKey`?

**Comment by ethauvin** [comment]
@aSemy Looking at the plugin docs, the [secion](https://docs.sonarqube.org/latest/analyzing-source-code/scanners/sonarscanner-for-gradle/) about multiple projects might help.

**Comment by aSemy** [comment]
Ahh that makes sense, thanks. I'll push an attempted fix soon.

**Comment by aSemy** [comment]
I've tried a few different approaches but unfortunately I can't figure out what the problem is.

I had a thought though: the aim is to migrate `:lib` to Kotlin/Multiplatform, [which SonarQube does not support](https://sonarsource.atlassian.net/browse/SONARKT-23). 

The `:app` project is going to remain as Kotlin/JVM, so I propose only adding SonarQube to that project. Hopefully it works, for now.

If that doesn't work, then how important is SonarQube for you? Could it be removed, or replaced with an alternative? Detekt still works.

**Comment by ethauvin** [comment]
> 
> The `:app` project is going to remain as Kotlin/JVM, so I propose only adding SonarQube to that project. Hopefully it works, for now.
> 

That would be great.

> If that doesn't work, then how important is SonarQube for you? Could it be removed, or replaced with an alternative? Detekt still works.

Not critical, but I'm not quite sure which other code coverage service would work.

E.

**Comment by aSemy** [comment]
Right, so I've tried a few different ways but I'm still getting the same error 

> Project not found. Please check the 'sonar.projectKey' and 'sonar.organization' properties, the 'SONAR_TOKEN' environment variable, or contact the project administrator

From what I can tell online this is related to the permissions granted to the token. I can only guess that Sonar was set up to only expect `:urlencoder:lib`, and is now getting confused because there's `:urlencoder:app`.

Can you experiment to see if there's any difference in the config (by setting `sonar.scanner.dumpToFile`) on this branch vs master?

> @aSemy Have you seen [this](https://community.sonarsource.com/t/does-sonarcloud-support-kotlin-multiplatform/9849)?

Yeah, I did see that. I actually had a look at the Sonarqube Gradle Plugin source to see if it's possible to update, but it's pretty outdated, unfortunately, so it would need a lot of re-writing. It's a pretty simple plugin though, and it's similar to plugins I've created on before, so in principle it's easy...

**Comment by ethauvin** [comment]
@aSemy I got sonar to work in the master branch with the following configuration:

```kotlin
sonarqube {
    properties {
        property("sonar.projectName", rootProject.name)
        property("sonar.projectKey", "ethauvin_${rootProject.name}")
        property("sonar.organization", "ethauvin-github")
        property("sonar.host.url", "https://sonarcloud.io")
        property("sonar.sourceEncoding", "UTF-8")
        property("sonar.sources", files("src/main/kotlin"))
        property("sonar.test", files("src/test/kotlin"))
        property("sonar.coverage.jacoco.xmlReportPaths", "build/reports/kover/report.xml")
    }
}
```

**Comment by aSemy** [comment]
Possibly the secret Sonar token isn't available on pull request branches? https://github.com/SonarSource/sonarqube-scan-action/issues/36#issuecomment-1402051603

What happens if you try checking my branch out locally and running `./gradlew sonar`?

**Comment by ethauvin** [comment]
> Possibly the secret Sonar token isn't available on pull request branches? [SonarSource/sonarqube-scan-action#36 (comment)](https://github.com/SonarSource/sonarqube-scan-action/issues/36#issuecomment-1402051603)
> 

I don't think so because `TESTS_BADGE_API_KEY` works, but just in case I made you a collaborator on the project which according to GitHub gives you access to the secrets.

Let me know if that helps.

**Comment by aSemy** [comment]
Thanks! No change, unfortunately. It still looks like an issue with permissions https://community.sonarsource.com/t/project-not-found-please-check-the-sonar-projectkey-and-sonar-organization-properties/67544/5

**Comment by ethauvin** [comment]
> Thanks! No change, unfortunately. It still looks like an issue with permissions https://community.sonarsource.com/t/project-not-found-please-check-the-sonar-projectkey-and-sonar-organization-properties/67544/5

Yeah, I tried running the fail job myself and still go the error.

**Comment by ethauvin** [comment]
@aSemy Let's forget about sonar for now, I have a suspicion it will resolve itself when we merge the branches.

**Comment by aSemy** [comment]
yeah, that makes sense. I'll do a bit of tidying and then mark the PR as ready.

**Review by ethauvin — COMMENTED** [review]
@aSemy  Cool! Thanks for all the work you've done on this.

**Comment by aSemy** [comment]
My pleasure! And we're only halfway there, the next step is Kotlin Multiplatform 😆

**Comment by ethauvin** [comment]
> My pleasure! And we're only halfway there, the next step is Kotlin Multiplatform smile

I've never done a multiplatform project before, I would have had to do a lot of research to get to this point.

**Comment by aSemy** [comment]
Ah cool. Kotlin Multiplatform itself is pretty easy, but the Gradle config is hard!

**Pull request merged**
